"""add job benefits

Revision ID: 049179ac8c5c
Revises: 273432282800
Create Date: 2026-08-25 23:26:59.619611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049179ac8c5c'
down_revision = '273432282800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vagas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beneficios', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vagas', schema=None) as batch_op:
        batch_op.drop_column('beneficios')

    # ### end Alembic commands ###
