"""link companies to users

Revision ID: 273432282800
Revises: 6242963073ea
Create Date: 2026-08-25 23:06:02.788555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273432282800'
down_revision = '6242963073ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_empresas_usuario_id'), ['usuario_id'], unique=True)
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_empresas_usuario_id'))
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
