"""add student professional profile data

Revision ID: 6242963073ea
Revises: be87cdd13ad1
Create Date: 2026-08-25 00:05:37.405045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6242963073ea'
down_revision = 'be87cdd13ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiencias_profissionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_profissional_id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=180), nullable=False),
    sa.Column('cargo', sa.String(length=180), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('atual', sa.Boolean(), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['perfil_profissional_id'], ['perfis_profissionais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiencias_profissionais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiencias_profissionais_perfil_profissional_id'), ['perfil_profissional_id'], unique=False)

    op.create_table('formacoes_academicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_profissional_id', sa.Integer(), nullable=False),
    sa.Column('instituicao', sa.String(length=180), nullable=False),
    sa.Column('curso', sa.String(length=180), nullable=False),
    sa.Column('tipo_formacao', sa.String(length=80), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('em_andamento', sa.Boolean(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['perfil_profissional_id'], ['perfis_profissionais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('formacoes_academicas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formacoes_academicas_perfil_profissional_id'), ['perfil_profissional_id'], unique=False)

    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_profissional_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=180), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('tecnologias', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['perfil_profissional_id'], ['perfis_profissionais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projetos_perfil_profissional_id'), ['perfil_profissional_id'], unique=False)

    with op.batch_alter_table('perfis_profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('sobre_mim', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('curriculo_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfis_profissionais', schema=None) as batch_op:
        batch_op.drop_column('curriculo_url')
        batch_op.drop_column('sobre_mim')
        batch_op.drop_column('foto_url')

    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projetos_perfil_profissional_id'))

    op.drop_table('projetos')
    with op.batch_alter_table('formacoes_academicas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formacoes_academicas_perfil_profissional_id'))

    op.drop_table('formacoes_academicas')
    with op.batch_alter_table('experiencias_profissionais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiencias_profissionais_perfil_profissional_id'))

    op.drop_table('experiencias_profissionais')
    # ### end Alembic commands ###
