"""create initial domain models

Revision ID: 703e5184cc7b
Revises: 
Create Date: 2026-08-07 18:18:30.942495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703e5184cc7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('setor', sa.String(length=120), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.Enum('linguagem', 'framework', 'banco_dados', 'ferramenta', 'conceito', 'outra', name='categoria_habilidade'), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habilidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habilidades_nome'), ['nome'], unique=True)

    op.create_table('tendencias_mercado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=150), nullable=False),
    sa.Column('tecnologia', sa.String(length=120), nullable=False),
    sa.Column('demanda', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('media_salarial', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_atualizacao', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('data_cadastro', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ativo', 'inativo', name='status_usuario'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('alertas_vaga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('palavra_chave', sa.String(length=120), nullable=True),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('modalidade', sa.Enum('presencial', 'hibrido', 'remoto', name='modalidade_alerta'), nullable=True),
    sa.Column('nivel_experiencia', sa.Enum('iniciante', 'junior', 'pleno', 'senior', name='nivel_experiencia_alerta'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alertas_vaga', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alertas_vaga_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('perfis_profissionais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nivel_experiencia', sa.Enum('iniciante', 'junior', 'pleno', 'senior', name='nivel_experiencia'), nullable=True),
    sa.Column('objetivo_profissional', sa.String(length=255), nullable=True),
    sa.Column('modalidade_preferida', sa.Enum('presencial', 'hibrido', 'remoto', name='modalidade_trabalho'), nullable=True),
    sa.Column('localizacao_preferida', sa.String(length=150), nullable=True),
    sa.Column('horas_semanais_estudo', sa.Integer(), nullable=True),
    sa.Column('pretensao_salarial', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('planos_estudo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=180), nullable=False),
    sa.Column('objetivo', sa.String(length=500), nullable=True),
    sa.Column('data_criacao', sa.Date(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim_prevista', sa.Date(), nullable=True),
    sa.Column('percentual_conclusao', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.Enum('nao_iniciado', 'em_andamento', 'pausado', 'concluido', name='status_plano'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planos_estudo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planos_estudo_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('vagas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=180), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('nivel_experiencia', sa.Enum('iniciante', 'junior', 'pleno', 'senior', name='nivel_experiencia_vaga'), nullable=False),
    sa.Column('modalidade', sa.Enum('presencial', 'hibrido', 'remoto', name='modalidade_vaga'), nullable=False),
    sa.Column('localizacao', sa.String(length=150), nullable=True),
    sa.Column('salario_minimo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salario_maximo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_publicacao', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ativa', 'pausada', 'encerrada', name='status_vaga'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vagas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vagas_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('etapas_estudo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_estudo_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=180), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('carga_horaria_estimada', sa.Integer(), nullable=True),
    sa.Column('data_inicio_prevista', sa.Date(), nullable=True),
    sa.Column('data_conclusao', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'em_andamento', 'concluida', name='status_etapa'), nullable=False),
    sa.ForeignKeyConstraint(['plano_estudo_id'], ['planos_estudo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etapas_estudo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etapas_estudo_plano_estudo_id'), ['plano_estudo_id'], unique=False)

    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alerta_vaga_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=180), nullable=False),
    sa.Column('mensagem', sa.String(length=500), nullable=False),
    sa.Column('data_envio', sa.Date(), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alerta_vaga_id'], ['alertas_vaga.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacoes_alerta_vaga_id'), ['alerta_vaga_id'], unique=False)

    op.create_table('perfil_habilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_profissional_id', sa.Integer(), nullable=False),
    sa.Column('habilidade_id', sa.Integer(), nullable=False),
    sa.Column('nivel_dominio', sa.Enum('basico', 'intermediario', 'avancado', name='nivel_habilidade'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['habilidade_id'], ['habilidades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perfil_profissional_id'], ['perfis_profissionais.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('perfil_profissional_id', 'habilidade_id', name='uq_perfil_habilidade')
    )
    op.create_table('plano_habilidades',
    sa.Column('plano_estudo_id', sa.Integer(), nullable=False),
    sa.Column('habilidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['habilidade_id'], ['habilidades.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plano_estudo_id'], ['planos_estudo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('plano_estudo_id', 'habilidade_id')
    )
    op.create_table('requisitos_vaga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vaga_id', sa.Integer(), nullable=False),
    sa.Column('habilidade_id', sa.Integer(), nullable=False),
    sa.Column('nivel_exigido', sa.Enum('basico', 'intermediario', 'avancado', name='nivel_habilidade_requisito'), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['habilidade_id'], ['habilidades.id'], ),
    sa.ForeignKeyConstraint(['vaga_id'], ['vagas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requisitos_vaga', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requisitos_vaga_habilidade_id'), ['habilidade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requisitos_vaga_vaga_id'), ['vaga_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requisitos_vaga', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requisitos_vaga_vaga_id'))
        batch_op.drop_index(batch_op.f('ix_requisitos_vaga_habilidade_id'))

    op.drop_table('requisitos_vaga')
    op.drop_table('plano_habilidades')
    op.drop_table('perfil_habilidades')
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacoes_alerta_vaga_id'))

    op.drop_table('notificacoes')
    with op.batch_alter_table('etapas_estudo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etapas_estudo_plano_estudo_id'))

    op.drop_table('etapas_estudo')
    with op.batch_alter_table('vagas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vagas_empresa_id'))

    op.drop_table('vagas')
    with op.batch_alter_table('planos_estudo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planos_estudo_usuario_id'))

    op.drop_table('planos_estudo')
    op.drop_table('perfis_profissionais')
    with op.batch_alter_table('alertas_vaga', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alertas_vaga_usuario_id'))

    op.drop_table('alertas_vaga')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    op.drop_table('tendencias_mercado')
    with op.batch_alter_table('habilidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habilidades_nome'))

    op.drop_table('habilidades')
    op.drop_table('empresas')
    # ### end Alembic commands ###
