"""add account type to users

Revision ID: be87cdd13ad1
Revises: 703e5184cc7b
Create Date: 2026-08-09 21:35:38.485830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be87cdd13ad1'
down_revision = '703e5184cc7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_conta', sa.Enum('estudante', 'empresa', name='tipo_conta'), server_default='estudante', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('tipo_conta')

    # ### end Alembic commands ###
